apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: kafka-service
  name: kafka-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-service
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: kafka-service
    spec:
      containers:
      - image: xocbayar/kafka-service
        name: kafka-service
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: kafka-service
  name: kafka-service
spec:
  ports:
  - name: 8100-8100
    port: 8100
    protocol: TCP
    targetPort: 8100
  selector:
    app: kafka-service
  type: ClusterIP
status:
  loadBalancer: {}
