apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: payment-service
  name: payment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: payment-service
    spec:
      containers:
      - image: xocbayar/payment-service
        name: payment-service
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: payment-service
  name: payment-service
spec:
  ports:
  - name: 9004-9004
    port: 9004
    protocol: TCP
    targetPort: 9004
  selector:
    app: payment-service
  type: LoadBalancer
status:
  loadBalancer: {}
