apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-config
data:
  dev-config.json:
    '{
      "spring.application.name": "notification-service",
      "server.port": "8110",
      "spring.kafka.bootstrap-servers": "localhost:9092",
      "spring.kafka.consumer.group-id": "gid",
      "spring.kafka.template.default-topic": "testing",
      "spring.data.mongodb.authentication-database": "admin",
      "spring.data.mongodb.port": "27017",
      "email.address": "finalprojectcs590@gmail.com"
     }'
#---
#apiVersion: v1
#kind: ConfigMap
#metadata:
#  name: special-config
#  namespace: default
#data:
#  special.how: very