#server:
#  port: 9001
#creditcard:
#  service:
#    key: creditcard-service
#spring:
#  application:
#    name: CREDITCARD-SERVICE
#  datasource:
#    # url: jdbc:h2:mem:creditcard-db
#    url: jdbc:h2:mem:CreditCardDb
#    username: sa
#    password:
#    driverClassName: org.h2.Driver
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
#    generate-ddl: true
#    show-sql: true
#    hibernate:
#      ddl-auto: create

